site_name: HepTrackTool
repo_url: https://github.com/xju2/heptracktool
site_description: A python package for track reconstruction workflow in HEP
site_author: Xiangyang Ju
theme:
  name: material
  palette:
    scheme: default
    accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_toc_entry: false
            show_if_no_docstring: true
            show_signature: true
            show_root_heading: true
            show_docstring_functions: false
            show_root_full_path: false
            show_docstring_attributes: false
            group_by_category: true
            docstring_style: google
            docstring_section_style: list
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: false

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Notebooks:
      - Graph Sparcification: notebooks/graph-sparcification.md
  - API Reference:
      - heptracktool:
          - io: api/heptracktool/io.md
          - models: api/heptracktool/models.md
          - tools: api/heptracktool/tools.md
          - utils: api/heptracktool/utils.md
          - viewer: api/heptracktool/viewer.md
  - Development: dev.md


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
